version: "3.8"

services:
  app:
    build: "./app"
    command: "/usr/local/bin/app -p 8080 --esh es0 --esp 9200"
    depends_on:
      - es0
    restart: always
    ports:
      - "8080:8080"
  es0:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.1"
    environment:
      - "discovery.type=single-node"
